export const TODO_LIST_REQUEST = "TODO_LIST_REQUEST"
export const TODO_LIST_SUCCESS = "TODO_LIST_SUCCESS"
export const TODO_LIST_FAIL = "TODO_LIST_FAIL"

export const TODO_ADD_REQUEST = "TODO_ADD_REQUEST"
export const TODO_ADD_SUCCESS = "TODO_ADD_SUCCESS"
export const TODO_ADD_FAIL = "TODO_ADD_FAIL"

export const TODO_DETAILS_REQUEST = "TODO_DETAILS_REQUEST"
export const TODO_DETAILS_SUCCESS = "TODO_DETAILS_SUCCESS"
export const TODO_DETAILS_FAIL = "TODO_DETAILS_FAIL"

export const TODO_DELETE_REQUEST = "TODO_DELETE_REQUEST"
export const TODO_DELETE_SUCCESS = "TODO_DELETE_SUCCESS"
export const TODO_DELETE_FAIL = "TODO_DELETE_FAIL"

export const TODO_UPDATE_REQUEST = "TODO_UPDATE_REQUEST"
export const TODO_UPDATE_SUCCESS = "TODO_UPDATE_SUCCESS"
export const TODO_UPDATE_FAIL = "TODO_UPDATE_FAIL"


