export const TODO_LIST_REQUEST = "TODO_LIST_REQUEST"
export const TODO_LIST_SUCCESS = "TODO_LIST_SUCCESS"
export const TODO_LIST_FAIL = "TODO_LIST_FAIL"

export const ADD_TODO_REQUEST = "ADD_TODO_REQUEST"
export const ADD_TODO_SUCCESS = "ADD_TODO_SUCCESS"
export const ADD_TODO_FAIL = "ADD_TODO_FAIL"

export const TODO_DETAILS_REQUEST = "TODO_DETAILS_REQUEST"
export const TODO_DETAILS_SUCCESS = "TODO_DETAILS_SUCCESS"
export const TODO_DETAILS_FAIL = "TODO_DETAILS_FAIL"

export const DELETE_TODO_REQUEST = "DELETE_TODO_REQUEST"
export const DELETE_TODO_SUCCESS = "DELETE_TODO_SUCCESS"
export const DELETE_TODO_FAIL = "DELETE_TODO_FAIL"


